apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    app.kubernetes.io/name: gosched-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gosched-agent
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gosched-agent
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (printf "%s-gosched" .Release.Name) }}
      {{- end }}
      hostPID: true
      containers:
        - name: agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args:
            - --master={{ .Release.Name }}-master:{{ .Values.master.service.grpcPort }}
            - --heartbeat={{ .Values.agent.config.heartbeatInterval }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: cgroup
              mountPath: /sys/fs/cgroup
            - name: data
              mountPath: /var/lib/gosched
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: data
          hostPath:
            path: /var/lib/gosched
            type: DirectoryOrCreate
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
