version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gosched-master
    main: ./cmd/gosched-master
    binary: gosched-master
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: gosched-agent
    main: ./cmd/gosched-agent
    binary: gosched-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: goschedctl
    main: ./cmd/goschedctl
    binary: goschedctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

dockers:
  - image_templates:
      - "ghcr.io/ilya-shevelev/gosched-master:{{ .Version }}"
      - "ghcr.io/ilya-shevelev/gosched-master:latest"
    dockerfile: deploy/docker/Dockerfile.master
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/ilya-shevelev/gosched-agent:{{ .Version }}"
      - "ghcr.io/ilya-shevelev/gosched-agent:latest"
    dockerfile: deploy/docker/Dockerfile.agent
    build_flag_templates:
      - "--platform=linux/amd64"
