FROM golang:1.22-alpine AS builder

RUN apk add --no-cache git ca-certificates

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /gosched-master ./cmd/gosched-master

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=builder /gosched-master /usr/local/bin/gosched-master

EXPOSE 9090 8080

USER nonroot:nonroot

ENTRYPOINT ["/usr/local/bin/gosched-master"]
